
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleproject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simpleproject
    spec:
      containers:
      - name: simpleproject
        image: simpleproject:latest
        imagePullPolicy: never
        ports:
        - name: http-port
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: simpleproject
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: simpleproject