
pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }

    stages {
        stage('scm') {
            steps {
                echo 'Getting from SCM..'
                checkout([$class: 'GitSCM', 
                          branches: [[name: '*/master']], 
                          doGenerateSubmoduleConfigurations: false, 
                          extensions: [], 
                          submoduleCfg: [], 
                          userRemoteConfigs: 
                          [[credentialsId: 'git_account', 
                            url: 'https://github.com/user/project.git']]])
                          
            }
        }
        stage('Build') {
            steps {
               configFileProvider(
                    [configFile(fileId: 'maven-settings', variable: 'MAVEN_SETTINGS')]) {
                    sh 'mvn -U -s $MAVEN_SETTINGS clean deploy'
                }
            }
        }
    }
}